### ISSUE TITLE
human36d Dataset preprocessing issues

### ISSUE THREAD

**Issue by xiaoTan12** [ShirleyMaxx/VirtualMarker#27]
I would like to ask whether the human36d data set has been processed by toolbox or is the original image. How do you preprocess the images?
    Because I encountered the following problem：
[ WARN:0@168.570] global loadsave.cpp:248 findDecoder imread_('./data/Human36M/images/s_07_act_16_subact_02_ca_01/s_07_act_16_subact_02_ca_01_000376.jpg'): can't open/read file: check file path/integrity
    main(args)
  File "main/main.py", line 94, in main
    n_iters_total_train = trainer.train(epoch, n_iters_total_train, master)
  File "/data/tx/VirtualMarker/virtualmarker/core/function.py", line 52, in train
    for i, meta in enumerate(batch_generator):
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/tx/Anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/tx/VirtualMarker/virtualmarker/dataset/multiple_datasets.py", line 26, in __getitem__
    return self.dbs[db_idx][data_idx]
  File "/data/tx/VirtualMarker/virtualmarker/dataset/human36m.py", line 100, in __getitem__
    return super().__getitem__(idx)
  File "/data/tx/VirtualMarker/virtualmarker/dataset/joints_dataset.py", line 182, in __getitem__
    img = load_img(img_path)
  File "/data/tx/VirtualMarker/virtualmarker/utils/preprocessing.py", line 11, in load_img
    img = cv2.imread(path, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)[:,:,::-1]
TypeError: 'NoneType' object is not subscriptable
    I would be very grateful if you could reply to me

**Comment by ShirleyMaxx** [comment]
We download and unzip to get the H3.6M images from [I2L-MeshNet](https://github.com/mks0601/I2L-MeshNet_RELEASE?tab=readme-ov-file#data).
